
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .kcm.namespace }}
  labels:
    app.kubernetes.io/instance: kcm-system
    app.kubernetes.io/part-of: k0rdent

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kcm
  namespace: {{ .kcm.namespace }}
spec:
  interval: 5m0s
  url: {{ .kcm.repository }}
  ref:
    tag: {{ .kcm.version }}

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kcm
  namespace: {{ .kcm.namespace }}
spec:
  chartRef:
    kind: OCIRepository
    name: kcm
    namespace: {{ .kcm.namespace }}
  interval: 10m
  values:
{{ .kcm.values | toYAML | strings.Indent 4 }}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kcm-controller-interaction
  namespace: {{ .flux.namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/instance: kcm-system
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: kcm
    ports:
    - port: http
  podSelector:
    matchLabels:
      app: source-controller
  policyTypes:
  - Ingress
